[theme]
base = "light"
primaryColor = "#2a78d6"
backgroundColor = "#f9f9f7"
secondaryBackgroundColor = "#f0efec"
textColor = "#1d1d1b"
font = "sans serif"
baseRadius = "small"
borderColor = "#e1e0d9"
showWidgetBorder = true

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
